name: 'OneMessage Robot Message'
description: 'onemessage robot message for github action'
author: 'cmcc-ict@gmail.com'
inputs:
  url:
    description: 'onemessage webhook'
    required: true

  type:
    description: 'message type'
    default: 'text'

  content:
    description: 'message content'
    required: true

  at:
    description: 'at users'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "blue"
  icon: "message-square"