name: 'OneMessage Robot Message'
description: 'onemessage robot message for github action'
author: 'cmcc-ict@gmail.com'
inputs:
  url:
    description: 'onemessage webhook'
    required: true

  robotKey:
    description: 'token'
    default: 'text'

  msg:
    description: 'message content'
    required: true

  failWhenError:
    description: 'fail when error '

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "blue"
  icon: "message-square"
  - name: onemessage robot message
